version: 2
updates:
  - package-ecosystem: bundler
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps

  - package-ecosystem: pip
    directory: /scripts
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      pip-patches:
        patterns:
          - "*"
        update-types:
          - patch

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps
    groups:
      github-actions-patches:
        patterns:
          - "*"
        update-types:
          - patch

  - package-ecosystem: npm
    directory: /e2e
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - dependencies
    commit-message:
      prefix: deps