permalink: /posts/:title/

paginate: 5
paginate_path: '/page/:num/'
excerpt_separator: '<!--more-->'
url: 'https://blog.jiwon.io'

sass:
  sass_dir: _sass
  style: 'compressed'

jekyll-archives:
  enabled:
    - tags
    - year
  permalinks:
    tag: '/archive/tag/:name/'
    year: '/archive/:year/'
  layouts:
    tag: tag
    year: year

plugins:
  - jekyll-paginate
  - jekyll-archives
